FROM python:3.11-slim

# Prevent Python from writing .pyc files and buffering logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV PYTHONPATH=/app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv pip install --system -r pyproject.toml

COPY backend/ ./backend/

COPY ml_pipeline/ ./ml_pipeline/

EXPOSE 8000

CMD ["fastapi", "run", "backend/main.py", "--port", "8000", "--host", "0.0.0.0"]