name: Nightly Pipeline Run

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      GCS_ACCESS_KEY: ${{ secrets.GCS_ACCESS_KEY }}
      GCS_SECRET_KEY: ${{ secrets.GCS_SECRET_KEY }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      STORAGE_MODE: ${{ vars.STORAGE_MODE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Run Feature Pipeline
        run: make feature-pipeline

      - name: Run Monitoring Pipeline
        id: monitor_step
        run: make monitoring-pipeline

      - name: Trigger Emergency Sweep (If Drifted)
        if: steps.monitor_step.outputs.drift_detected == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Drift detected. Triggering the Sweep workflow."
          gh workflow run sweep.yaml

      - name: Run Training Pipeline
        if: steps.monitor_step.outputs.drift_detected != 'true'
        run: make training-pipeline

      - name: Trigger Model Refresh on VPS
        run: |
          curl -X POST http://${{ vars.VPS_IP }}/api/refresh-model