name: Project Setup
# This workflow is intended for the start of the project.
# It does a backfill, sweep trains, picks champion, turns champion into artifact, makes predictions and if backend is already online, hot-swaps the model.

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Backfill Start Date (YYYY-MM-DD). Do not enter a date before 2014-09-17 (No data exists prior)!'
        required: true
        default: '2016-06-01'
        type: string

permissions:
  contents: write
  actions: write

jobs:
  genesis-backfill:
    runs-on: ubuntu-latest
    
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./.secrets/gcp-key-pipeline.json
      GCS_BUCKET_NAME: ${{ vars.GCS_BUCKET_NAME }}
      STORAGE_MODE: ${{ vars.STORAGE_MODE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create GCP Credentials File
        run: |
          mkdir -p .secrets
          echo '${{ secrets.GCP_PIPELINE_KEY_JSON }}' > .secrets/gcp-key-pipeline.json

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Historical Backfill
        run: make backfill START_DATE=${{ github.event.inputs.start_date }}

  trigger-sweep:
    needs: genesis-backfill
    uses: ./.github/workflows/sweep.yaml
    secrets: inherit