name: Project Setup
# This workflow is intended for the start of the project.
# It does a backfill, sweep trains, picks champion, turns champion into artifact, makes predictions and if backend is already online, hot-swaps the model.

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  genesis-backfill:
    runs-on: ubuntu-latest
    
    env:
      GCS_ACCESS_KEY: ${{ secrets.GCS_ACCESS_KEY }}
      GCS_SECRET_KEY: ${{ secrets.GCS_SECRET_KEY }}
      GCS_BUCKET_NAME: ${{ vars.GCS_BUCKET_NAME }}
      STORAGE_MODE: ${{ vars.STORAGE_MODE }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v3

      - name: Historical Backfill
        run: make backfill

  trigger-sweep:
    needs: genesis-backfill
    uses: ./.github/workflows/sweep.yaml
    secrets: inherit